server:
  port: 8080
  error:
    include-message: always

spring:
#  liquibase:
#    change-log: classpath:db/changelog/changelog-master.xml
#    liquibase-schema: base
#    default-schema: base
  datasource:
    url: jdbc:h2:file:D:/data/test
    username: root
    password: 123456
    driver-class-name: org.h2.Driver
#    url: jdbc:postgresql://localhost:5432/?
#    username: postgres
#    password:
#    show-sql: true
#    url: jdbc:mysql://localhost:3306/?
#    username: root
#    password:
#    driver-class-name: com.mysql.jdbc.Driver
  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
#      ddl-auto: update
      ddl-auto: create-drop
  application:
    name: base-backend
  h2:
    console:
      enabled: true

logging:
  level:
    com.example.basebackend: INFO
    org.hibernate: INFO
#  file.path: D:/logs
#  file.name: ${logging.file.path}/base.log